#!/bin/bash 
# Kevin Becker, June 9 2023
# alpha_job

SHORE_REPO="moos-ivp"
SHORE_MISSION="ivp/missions/s1_alpha"
warp=5
if [[ $warp -gt $MONTE_MOOS_MAX_WARP ]]; then
	warp=$MONTE_MOOS_MAX_WARP
fi
SHORE_FLAGS=" --nogui $warp"  
JOB_TIMEOUT=60 # (timewarp is not accounted)
SHORE_TARG="alpha.moos++"  # Targ file for the shore mission

